macos_titlebar_color                    background

background                              #fdf6e3
foreground                              #657b83
inactive_tab_background                 #eee8d5
inactive_tab_foreground                 #657b83
active_tab_background                   #eee8d5
active_tab_foreground                   #d33682
inactive_border_color                   #eee8d5
active_border_color                     #6c71c4
bell_border_color                       #dc322f
cursor                                  #657b83
cursor_text_color                       #fdf6e3
selection_background                    #ffd740
selection_foreground                    #002b36
url_color                               #268bd2
color0                                  #eee8d5
color1                                  #dc322f
color2                                  #859900
color3                                  #b58900
color4                                  #268bd2
color5                                  #d33682
color6                                  #2aa198
color7                                  #073642
color8                                  #fdf6e3
color9                                  #cb4b16
color10                                 #93a1a1
color11                                 #839496
color12                                 #657b83
color13                                 #6c71c4
color14                                 #586e75
color15                                 #002b36
