hs.hotkey.bind("⌃⌥⇧⌘", "b", function() hs.application.launchOrFocus("Firefox.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "c", function() hs.application.launchOrFocus("Google Chrome.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "f", function() hs.application.launchOrFocus("Finder.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "g", function() hs.application.launchOrFocus("Chat.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "h", function() hs.application.launchOrFocus("Audio Hijack.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "i", function() hs.application.launchOrFocus("Sublime Text.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "j", function() hs.application.launchOrFocus("Sublime Merge.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "k", function() hs.application.launchOrFocus("Activity Monitor.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "m", function() hs.application.launchOrFocus("Messages.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "n", function() hs.application.launchOrFocus("Obsidian.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "o", function() hs.application.launchOrFocus("OmniFocus.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "p", function() hs.application.launchOrFocus("Photo Booth.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "r", function() hs.application.launchOrFocus("Calendar.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "s", function() hs.application.launchOrFocus("Spotify.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "t", function() hs.application.launchOrFocus("iTerm.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "u", function() hs.application.launchOrFocus("UlyssesMac.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "v", function() hs.application.launchOrFocus("MacVim.app") end)
hs.hotkey.bind("⌃⌥⇧⌘", "y", function() hs.application.launchOrFocus("Dictionary.app") end)
