notARepository: quit

update:
  method: never

refresher:
  refreshInterval: 20  # seconds
  externalChangeCheckInterval: 20  # seconds

git:
  autoFetch: false
  diffContextSize: 999_999
  diffRenderers:
    - command: delta --paging never --features light-unified-diff
      name: Unified Diff Light
    - command: delta --paging never --features  dark-unified-diff
      name: Unified Diff Dark
    - command: delta --paging never --features light-side-by-side
      name: Side-By-Side Light
    - command: delta --paging never --features  dark-side-by-side
      name: Side-By-Side Dark

gui:
  showBottomLine: false
  showFileTree: false
  showListFooter: false
  showPanelJumps: false
  showRandomTip: false
  showRootItemInFileTree: false
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 10
  shrinkSidePanelsToContent: false
  sidePanels:
    - [files]
    - [commits, branches]
  fileTreeSortOrder: foldersFirst
  commitAuthorShortLength: 0
  commandLogSize: 4
  scrollPastBottom: false
  scrollOffMargin: 3
  scrollHeight: 3
  border: bold
  theme:
    inactiveBorderColor:
      - yellow
    activeBorderColor:
      - magenta
    searchingActiveBorderColor:
      - cyan
    inactiveViewSelectedLineBgColor:
      - black
    selectedLineBgColor:
      - reverse

keybinding:
  universal:
    nextScreenMode:                   <alt+m>
    prevScreenMode:             <shift+alt+m>
    cycleDiffRenderers:               <alt+i>
    cycleDiffRenderersReverse:  <shift+alt+i>
