#!/usr/bin/env python3

import argparse

RESET  = '\033[0m'

COLORS = [
    ('Normal',                    '\033[0m'),
    ('Black',                     '\033[30m'),
    ('Red',                       '\033[31m'),
    ('Green',                     '\033[32m'),
    ('Yellow',                    '\033[33m'),
    ('Blue',                      '\033[34m'),
    ('Magenta',                   '\033[35m'),
    ('Cyan',                      '\033[36m'),
    ('White',                     '\033[37m'),
    ('Bright Black',              '\033[30;1m'),
    ('Bright Red',                '\033[31;1m'),
    ('Bright Green',              '\033[32;1m'),
    ('Bright Yellow',             '\033[33;1m'),
    ('Bright Blue',               '\033[34;1m'),
    ('Bright Magenta',            '\033[35;1m'),
    ('Bright Cyan',               '\033[36;1m'),
    ('Bright White',              '\033[37;1m'),
    ('Aixterm Black',             '\033[90m'),
    ('Aixterm Red',               '\033[91m'),
    ('Aixterm Green',             '\033[92m'),
    ('Aixterm Yellow',            '\033[93m'),
    ('Aixterm Blue',              '\033[94m'),
    ('Aixterm Magenta',           '\033[95m'),
    ('Aixterm Cyan',              '\033[96m'),
    ('Aixterm White',             '\033[97m'),
    ('Background Black',          '\033[40m'),
    ('Background Red',            '\033[41m'),
    ('Background Green',          '\033[42m'),
    ('Background Yellow',         '\033[43m'),
    ('Background Blue',           '\033[44m'),
    ('Background Magenta',        '\033[45m'),
    ('Background Cyan',           '\033[46m'),
    ('Background White',          '\033[47m'),
    ('Background Bright Black',   '\033[40;1m'),
    ('Background Bright Red',     '\033[41;1m'),
    ('Background Bright Green',   '\033[42;1m'),
    ('Background Bright Yellow',  '\033[43;1m'),
    ('Background Bright Blue',    '\033[44;1m'),
    ('Background Bright Magenta', '\033[45;1m'),
    ('Background Bright Cyan',    '\033[46;1m'),
    ('Background Bright White',   '\033[47;1m'),
    ('Background Aixterm Black',  '\033[100m'),
    ('Background Aixterm Red',    '\033[101m'),
    ('Background Aixterm Green',  '\033[102m'),
    ('Background Aixterm Yellow', '\033[103m'),
    ('Background Aixterm Blue',   '\033[104m'),
    ('Background Aixterm Magenta','\033[105m'),
    ('Background Aixterm Cyan',   '\033[106m'),
    ('Background Aixterm White',  '\033[107m'),
]

def print_table_header(columns):
  print(('{:11}  ' * len(columns)).format(*columns))
  print('─' * (13 * len(columns) - 2))

def parse_command_line_arguments():
  parser = argparse.ArgumentParser()

  parser.add_argument(
      '-v', '--verbose', dest='verbose', action='store_true',
      help='enable verbose output')

  return parser.parse_args()

def main():
  args = parse_command_line_arguments()

  if args.verbose:
    for name, escape_code in COLORS:
      print('{:26} : {}Lorem Ipsum{}'.format(name, escape_code, RESET))
  else:
    lorem_ipsum = '{}Lorem Ipsum{}  ' * 8

    print_table_header([
        'Foreground', 'Bright', 'Aixterm', 'Bright Aix',
        'Background', 'Bright', 'Aixterm', 'Bright Aix',
        ])
    for i in range(8):
      print(lorem_ipsum.format(
          '\033['      + str( 30 + i) +   'm', RESET,
          '\033['      + str( 30 + i) + ';1m', RESET,
          '\033['      + str( 90 + i) +   'm', RESET,
          '\033['      + str( 90 + i) + ';1m', RESET,
          '\033['      + str( 40 + i) +   'm', RESET,
          '\033['      + str( 40 + i) + ';1m', RESET,
          '\033['      + str(100 + i) +   'm', RESET,
          '\033['      + str(100 + i) + ';1m', RESET,
          ))

    print()
    print_table_header([
        'base03    8', 'base02    0', 'base01   10', 'base00   11',
        'base0    12', 'base1    14', 'base2     7', 'base3    15',
        ])
    for i in range(8):
      print(lorem_ipsum.format(
          '\033[30;1;' + str( 40 + i) +   'm', RESET,  # base03 - bright black
          '\033[30;'   + str( 40 + i) +   'm', RESET,  # base02 - black
          '\033[32;1;' + str( 40 + i) +   'm', RESET,  # base01 - bright green
          '\033[33;1;' + str( 40 + i) +   'm', RESET,  # base00 - bright yellow
          '\033[34;1;' + str( 40 + i) +   'm', RESET,  # base0  - bright blue
          '\033[36;1;' + str( 40 + i) +   'm', RESET,  # base1  - bright cyan
          '\033[37;'   + str( 40 + i) +   'm', RESET,  # base2  - white
          '\033[37;1;' + str( 40 + i) +   'm', RESET,  # base3  - bright white
          ))

    print()
    print_table_header([
        'base03  Aix', 'base02  Aix', 'base01  Aix', 'base00  Aix',
        'base0   Aix', 'base1   Aix', 'base2   Aix', 'base3   Aix',
        ])
    for i in range(8):
      print(lorem_ipsum.format(
          '\033[30;1;' + str(100 + i) +   'm', RESET,  # base03 - bright black
          '\033[30;'   + str(100 + i) +   'm', RESET,  # base02 - black
          '\033[32;1;' + str(100 + i) +   'm', RESET,  # base01 - bright green
          '\033[33;1;' + str(100 + i) +   'm', RESET,  # base00 - bright yellow
          '\033[34;1;' + str(100 + i) +   'm', RESET,  # base0  - bright blue
          '\033[36;1;' + str(100 + i) +   'm', RESET,  # base1  - bright cyan
          '\033[37;'   + str(100 + i) +   'm', RESET,  # base2  - white
          '\033[37;1;' + str(100 + i) +   'm', RESET,  # base3  - bright white
          ))

if __name__ == '__main__':
  main()
