#!/usr/bin/env python3

import dataclasses
import importlib.metadata
import re
import subprocess

import packaging.version

from serban.dotfiles.script import RESET, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN

VIM_REGEX = r'VIM - Vi IMproved (.+) \(.*\s.*\sIncluded patches: 1-(.+)'

@dataclasses.dataclass
class Package:
  name: str
  args: list[str]
  regx: str
  date: str
  okay: str
  want: str
  have: str = '∅'
  colo: str = RED
  mark: str = '✗'

packages = [
    Package('bat',       ['bat', '--version'],       r'bat (.+)',           '2023-08-18', '0.22.1',   '0.23.0'),
    Package('click',     None,                       None,                  '2023-10-31', '8.1.3',    '8.1.7'),
    Package('delta',     ['delta', '--version'],     r'\033\[0mdelta (.+)', '2023-08-18', '0.16.5',   '0.16.5'),
    Package('fd',        ['fd', '--version'],        r'fd(?:find)? (.+)',   '2023-08-18', '8.6.0',    '8.7.0'),
    Package('fish',      ['fish', '--version'],      r'fish, version (.+)', '2023-08-18', '3.6.0',    '3.6.1'),
    Package('fzf',       ['fzf', '--version'],       r'(.+) \(.*',          '2023-08-18', '0.38.0',   '0.42.0'),
    Package('git',       ['git', '--version'],       r'git version (.+)',   '2023-08-18', '2.39.2',   '2.41.0'),
    Package('less',      ['less', '--version'],      r'less (.+) \(.*',     '2023-08-18', '590',      '643'),
    Package('lf',        ['lf', '--version'],        r'r?(.+)',             '2023-08-18', '28',       '30'),
    Package('neovim',    ['nvim', '--version'],      r'NVIM v(.+)',         '2023-08-18', '0.9.1',    '0.9.1'),
    Package('packaging', None,                       None,                  '2023-10-31', '23.0',     '23.2'),
    Package('python',    ['python3', '--version'],   r'Python (.+)',        '2023-08-18', '3.11.2',   '3.11.4'),
    Package('rich',      None,                       None,                  '2023-10-31', '13.3.1',   '13.6.0'),
    Package('tmux',      ['tmux', '-V'],             r'tmux (.+)',          '2023-08-18', '3.3a',     '3.3a'),
    Package('vim',       ['vim', '--version'],       VIM_REGEX,             '2023-08-18', '9.0.1378', '9.0.1700'),
    Package('watchexec', ['watchexec', '--version'], r'watchexec (\S+)',    '2023-08-21', '1.22.3',   '1.22.3'),
]

for p in packages:
  if p.args:
    try:
      output = subprocess.run(
          p.args, check=True, stdout=subprocess.PIPE).stdout.decode().strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
      continue

    m = re.match(p.regx, output)
    if not m:
      continue

    p.have = m.group(1) if p.name != 'vim' else f'{m.group(1)}.{m.group(2)}'
  else:
    p.have = importlib.metadata.version(p.name)

  okay = packaging.version.parse(p.okay)
  want = packaging.version.parse(p.want)

  try:
    have = packaging.version.parse(p.have)
  except packaging.version.InvalidVersion:
    have = packaging.version.parse('0')

  if have >= okay:
    p.colo = YELLOW
    p.mark = '·'

  if have == want:
    p.colo = GREEN
    p.mark = '✓'

  if have > want:
    p.colo = CYAN
    p.mark = '✓'

for p in packages:
  print(f'{p.colo}{p.mark}{RESET}  {p.name:9}  {p.okay:8}  {p.want:8}  {p.colo}{p.have:8}{RESET}')
