#!/usr/bin/env python3

import dataclasses
import re
import subprocess

import packaging.version

RESET  = '\033[0m'
RED    = '\033[31m'
GREEN  = '\033[32m'
YELLOW = '\033[33m'
CYAN   = '\033[36m'

VIM_REGEX = r'VIM - Vi IMproved (.+) \(.*\s.*\sIncluded patches: 1-(.+)'

@dataclasses.dataclass
class Package:
  name: str
  args: list[str]
  regx: str
  date: str
  okay: str
  want: str
  have: str = '∅'
  colo: str = RED
  mark: str = '✗'

packages = [
    Package('bat',    ['bat', '--version'],     r'bat (.+)',           '2022-05-15', '0.21.0',   '0.21.0'),
    Package('delta',  ['delta', '--version'],   r'\033\[0mdelta (.+)', '2022-05-15', '0.13.0',   '0.13.0'),
    Package('fd',     ['fd', '--version'],      r'fd (.+)',            '2022-05-15', '8.3.2',    '8.3.2'),
    Package('fish',   ['fish', '--version'],    r'fish, version (.+)', '2022-05-15', '3.4.0',    '3.4.1'),
    Package('fzf',    ['fzf', '--version'],     r'(.+) \(.*',          '2022-05-15', '0.30.0',   '0.30.0'),
    Package('git',    ['git', '--version'],     r'git version (.+)',   '2022-05-15', '2.36.1',   '2.36.1'),
    Package('less',   ['less', '--version'],    r'less (.+) \(.*',     '2022-05-15', '590',      '590'),
    Package('lf',     ['lf', '--version'],      r'r?(.+)',             '2022-05-15', '27',       '27'),
    Package('python', ['python3', '--version'], r'Python (.+)',        '2022-05-15', '3.9.10',   '3.10.4'),
    Package('tmux',   ['tmux', '-V'],           r'tmux (.+)',          '2022-05-15', '3.2a',     'next-3.4'),
    Package('vim',    ['vim', '--version'],     VIM_REGEX,             '2022-05-15', '8.2.3995', '8.2.4900'),
]

for p in packages:
  try:
    output = subprocess.run(
        p.args, check=True, stdout=subprocess.PIPE).stdout.decode().strip()
  except (FileNotFoundError, subprocess.CalledProcessError):
    continue

  m = re.match(p.regx, output)
  if not m:
    continue

  p.have = m.group(1) if p.name != 'vim' else f'{m.group(1)}.{m.group(2)}'

  okay = packaging.version.parse(p.okay)
  want = packaging.version.parse(p.want)
  have = packaging.version.parse(p.have)

  if have >= okay:
    p.colo = YELLOW
    p.mark = '·'

  if have == want:
    p.colo = GREEN
    p.mark = '✓'

  if have > want:
    p.colo = CYAN
    p.mark = '✓'

for p in packages:
  print(f'{p.colo}{p.mark}{RESET}  {p.name:6}  {p.okay:8}  {p.want:8}  {p.colo}{p.have:8}{RESET}')
