#!/usr/bin/env python3

import datetime
import sys

def date_range_inclusive(start_date, end_date):
  for i in range((end_date - start_date).days + 1):
    yield start_date + datetime.timedelta(days=i)

def main():
  if len(sys.argv) < 3:
    print('Provide a start date and end date', file=sys.stderr)
    sys.exit(1)

  start_date = datetime.datetime.strptime(sys.argv[1], '%Y-%m-%d').date()
  end_date   = datetime.datetime.strptime(sys.argv[2], '%Y-%m-%d').date()

  for date in date_range_inclusive(start_date, end_date):
    print(date.strftime('%a %b %d'))

if __name__ == '__main__':
  main()
