#!/usr/bin/env python3

import calendar
import datetime
import sys

year = datetime.date.today().year

if len(sys.argv) > 1:
  year = int(sys.argv[1])

first_day = datetime.date(year, 1, 1)
last_day = datetime.date(year, 12, 31)

first_monday = first_day + datetime.timedelta(
    days=((calendar.MONDAY - first_day.weekday() + 7) % 7))

date = first_monday

while date < last_day:
  print(date.strftime('%Y-%m-%d'))
  date += datetime.timedelta(weeks=1)
