#!/usr/bin/env python3

# See "Box Drawing": https://www.unicode.org/charts/PDF/U2500.pdf

import argparse
import collections


Style = collections.namedtuple('Style', 'horizontal_line')

STYLES = {
    'ascii':  Style('-'),
    'light':  Style('─'),
    'heavy':  Style('━'),
    'double': Style('═'),
}


def parse_command_line_arguments():
  parser = argparse.ArgumentParser(
      description='sep prints a nice horizontal line.')

  parser.add_argument(
      '-s', '--style', dest='style', choices=STYLES.keys(), default='light',
      help='the style of the line')

  parser.add_argument(
      '-w', '--width', dest='width', type=int, default=80,
      help='the width of the line')

  return parser.parse_args()


def main():
  args = parse_command_line_arguments()
  assert args.width > 0

  print(STYLES[args.style].horizontal_line * args.width)


if __name__ == '__main__':
  main()
