#!/usr/bin/env python3

import calendar
import datetime
import pathlib
import stat
import string
import subprocess

TEMPLATE = """## Week of $MONTH $DAY, $YEAR

### Monday

### Tuesday

### Wednesday

### Thursday

### Friday
"""

def snippets_path(date):
  return pathlib.Path(
      pathlib.Path.home(), 'snippets',
      'snippets-' + date.isoformat() + '.md')


def write_snippets_file(date):
  substitutions = {
    'MONTH': calendar.month_name[date.month],
    'DAY': date.day,
    'YEAR': date.year,
  }

  template = string.Template(TEMPLATE)

  path = snippets_path(date)
  path.parent.mkdir(parents=True, exist_ok=True)

  with path.open('w') as f:
    f.write(template.substitute(substitutions))

  path.parent.chmod(stat.S_IRWXU)
  path.chmod(stat.S_IRUSR | stat.S_IWUSR)


def open_vim(left_path, right_path):
  subprocess.run(
      ['vim',
       '-c', 'wincmd l',
       '-c', 'silent bufdo set textwidth=0',
       '-O', left_path, right_path])


def main():
  today = datetime.date.today()
  this_monday = today - datetime.timedelta(days=today.weekday())
  last_monday = this_monday - datetime.timedelta(weeks=1)

  this_week_path = snippets_path(this_monday)
  last_week_path = snippets_path(last_monday)

  if not this_week_path.exists():
    write_snippets_file(this_monday)

  open_vim(last_week_path, this_week_path)


if __name__ == '__main__':
  main()
